---
- name: Create users
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    state: present
    create_home: yes
  loop: "{{ users_list }}"

- name: Add users to sudo group
  user:
    name: "{{ item.name }}"
    groups: sudo
    append: yes
  loop: "{{ users_list }}"
